### ISSUE TITLE
Allow "find in page" or provide alternative means for searching

### ISSUE THREAD

**Issue by OliverJAsh** [webpack-contrib/webpack-bundle-analyzer#123]
Firstly, thanks for the helpful tool!

I want to search the tree for a module to finds its size. The built-in "find in page" browser feature doesn't work, presumably because the DOM is not being used. If that's the case, could this switch to using the DOM? Or, can we provide alternative means for searching the tree?

Note that find in page does work for [source-map-explorer](https://github.com/danvk/source-map-explorer).

**Comment by valscion** [comment]
Hi! Thanks for the issue. I've found myself needing such a feature, too. Unfortunately, currently it is not possible.

You're right about the visualizer "not using DOM", because [Carrot Search FoamTree](https://get.carrotsearch.com/foamtree/demo/demos/index.html) (the visualization we use) renders the content to `<canvas>` tag and thus the output is not searchable.

Quickly glancing at the [FoamTree API](https://get.carrotsearch.com/foamtree/demo/api/index.html), I couldn't find a way to implement search functionality. I'd be happy to be proven wrong, though :smile:

Hopefully I will at some point in the future get #97 completed so that we can have different visualizers. This would allow building something like the one source-map-explorer uses, so that the visualization would be more accessible.

Let me know if you have any more questions!

**Comment by OliverJAsh** [comment]
Thanks for the detailed response @valscion!

Would you consider switching to a different treemap renderer? This one looks quite good: [webtreemap](https://github.com/evmar/webtreemap). It uses the DOM rather than canvas/SVG, which of course means you get the benefits of accessibility.

I believe https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/97 would have allowed for this, but unfortunately that PR now seems to be closed.

**Comment by valscion** [comment]
I think it might be a bit of a hassle to move to a different treemap renderer. I'm not sure if it's something @th0r would want to do — if he does, then things might be different. I'm not in the position to make the decision to change the renderer to a different one :relaxed:

#97 would've precisely allowed this feature to succeed. Unfortunately I didn't have the motivation nor the time to get that PR to completion. Maybe some day I'll try again

**Comment by th0r** [comment]
`v3` with modules search feature is published.
