### ISSUE TITLE
Allow "Grouping" and other selectors to find a specific module in all the modules 

### ISSUE THREAD

**Issue by thebedroomprogrammer** [webpack-contrib/webpack-bundle-analyzer#124]
Thanks for making such a simple tool to analyse the dependencies in my react project.

I was just thinking if the future release can have features like "Grouping" , "Selecting" or "Searching" a specific module like in this example at https://get.carrotsearch.com/foamtree/latest/demos/ft500.html

**Comment by valscion** [comment]
Hi! Thanks for the idea! We could utilize these features somehow. It'd be nice to see a design or a proof of concept of these ideas, so that we could discuss something more concrete and form opinions based on that.

If we'll ever want to think about the current reporter design more thoroughly, then utilizing these grouping/selecting/searching features would be a nice improvement.

I think we've got a few issues in here that could be implemented with similar functionality. At least #123 pops to my mind, which was about needing search functionality. If you find other issues in the issue tracker, feel free to link to them as a new comment here so we could keep track of them :)

**Comment by olee** [comment]
This would be nice to group by asset type like css, html and js!

**Comment by Frozzy6** [comment]
I'm voting for searching implementation first
I think it's an essential part of functionality especially when you check bundle of a large application.

**Comment by th0r** [comment]
@thebedroomprogrammer could you try `v3` and see if the new modules searching feature solves the issue for you?

**Comment by thebedroomprogrammer** [comment]
I can't thank you enough for this. It's working absolutely fine. The search high lighting feature is also great.

**Comment by th0r** [comment]
Thanks! Closing it then.
