### ISSUE TITLE
Can't recognize import  key word

### ISSUE THREAD

**Issue by yankwan** [webpack-contrib/webpack-bundle-analyzer#127]
When I run the common `webpack --profile --json > stats.json`, it report such error:

    import webpack from 'webpack';
    ^^^^^^

    SyntaxError: Unexpected reserved word
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)

It seems that it can't resolved the key word `import`, what I did in webpack.config.js looks like

    var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
    import webpack from 'webpack';
    import config  from './config';

    export default {
        entry: {
             ...
        }
    }

    plugins: [
        new BundleAnalyzerPlugin()
    ]

**Comment by valscion** [comment]
Hi,

thanks for the issue! This particular case is `webpack` command crashing, not our plugin.

As node.js, which runs the `webpack` command on your computer, does not yet support `import` keyword, you will need to use `require` instead of `import` in your webpack configurations.

Hope this helps! Have a great day
