### ISSUE TITLE
Understanding the output

### ISSUE THREAD

**Issue by gkatsanos** [webpack-contrib/webpack-bundle-analyzer#133]
![image](https://user-images.githubusercontent.com/1768834/32993653-878ed6ec-cd5b-11e7-83ff-15d9ebc51d96.png)

Does this mean some things are loaded twice/tree shaking isn't working? (for example vue.esm)

**Comment by valscion** [comment]
It looks like vue2-leaflet has its own version of vue npm module bundled in. Maybe it requires a different version of vue compared to your application?

Try `npm ls vue` -- you should only have one instance of vue there, but I think you'll find otherwise

**Comment by gkatsanos** [comment]
Does this help? https://github.com/KoRiGaN/Vue2Leaflet/blob/master/package.json
I also posted an issue to their tracker.

**Comment by valscion** [comment]
It might be that the version constraint of `vue` you have in your project's `package.json` is incompatible with what `vue2-leaflet` has (the one you linked).

It might be that `vue2-leaflet` should use `peerDependencies` instead of `dependencies` to specify the required version of `vue`. That might fix the issue of duplicated `vue` module.

I'll close this issue for now, as this is more of a support case than an issue in `webpack-bundle-analyzer`. I hope you'll find your answer :relaxed:

I'll still answer your original question:

> Does this mean some things are loaded twice/tree shaking isn't working?

Yes, I'd think so.

**Comment by gkatsanos** [comment]
Thank you! that's all very informative and I will investigate it to further understand the behavior of the bundler and dependencies/peerDependencies .
